# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee777896fa4bd50f7b0d7d61d3ac367c6522e508d4d7ce1b82d47854b33a3943625338fc2d975ba562b55f32626bd785c4e4464eae09fb2ab322fc6090c9069e

test:
  secret_key_base: cdc2e1fd7f57f1d1a640c24537a3a70535d36a3c2a2804cc89004f50075db62bf3ec7514345e020f16aa870595c99c950735ee889983a2c9e689a0245a4d5c1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
